# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pdfkit}
  s.version = "0.4.6"

  s.required_rubygems_version = ">= 1.3.6"
  s.authors = ["jdpace"]
  s.date = %q{2010-12-27}
  s.description = %q{Uses wkhtmltopdf to create PDFs using HTML}
  s.email = %q{jared@codewordstudios.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.platform = Gem::Platform::RUBY
  s.files = `git ls-files`.split("\n")
  s.executables = `git ls-files`.split("\n").map{|f| f =~ /^bin\/(.*)/ ? $1 : nil}.compact
  s.require_path = 'lib'
  s.homepage = %q{http://github.com/jdpace/PDFKit}
  s.post_install_message = %q{******************************************************************

Install wkhtmltopdf:

1. Install by hand (recomended):

        https://github.com/jdpace/PDFKit/wiki/Installing-WKHTMLTOPDF

2. Try using the wkhtmltopdf-binary gem (mac + linux i386)

        gem install wkhtmltopdf-binary


******************************************************************
}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{HTML+CSS -> PDF}
  s.test_files = [
    "spec/middleware_spec.rb",
     "spec/pdfkit_spec.rb",
     "spec/source_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.0.0.beta.8"])
      s.add_development_dependency(%q<rspec-core>, ["~> 2.0.0.beta.8"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.0.0.beta.8"])
      s.add_dependency(%q<rspec-core>, ["~> 2.0.0.beta.8"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.0.0.beta.8"])
    s.add_dependency(%q<rspec-core>, ["~> 2.0.0.beta.8"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
  end
end

